version: "3.9"
services:
  simple-blog:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_HOST=mongo
      - DB_PORT=27017
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./database/mongodb:/data/db
    ports:
      - "27017:27017"